import { create } from "zustand";
export const store = create((set) => ({
  // --- Global states ---
  sendEnabledSt: true,
  isLoadingSt: false,
  themeSt: 'black',
  isInForegroundSt: true,
  userTypeSt: '',
  userNameSt: '',
  screenSelectedSt: '',
  isConnectedToInternetSt: true,
  wifiNameSt: '',
  networkTypeSt: '',
  supabaseTimeoutSt: false,
  rokuSearchModeSt: 'default',
  screensSt: [],
  cableChannelsSt: [],
  youtubeSearchVideosSt: [],
  youtubeChannelsLizSt: [],
  youtubeVideosLizSt: [],
  rokuAppsSt: [],
  hdmiSalaSt: [],
  devicesSt: [],
  rokuPlayStatePositionSt: 0,
  isPcSt: false,
  isAppSt: false,
  peersSt: [],
  leaderSt: '',
  viewSt: { selected: '', cable: { channels: { category: [] } }, roku: { apps: { selected: '', youtube: { mode: '', channel: '' } } }, devices: { device: '' } },

  // --- Actions ---
  setSendEnabledSt: (v) => set({ sendEnabledSt: v }),
  setIsLoadingSt: (v) => set({ isLoadingSt: v }),
  setThemeSt: (v) => set({ themeSt: v }),
  setIsInForegroundSt: (v) => set({ isInForegroundSt: v }),
  setUserTypeSt: (v) => set({ userTypeSt: v }),
  setUserNameSt: (v) => set({ userNameSt: v }),
  setScreenSelectedSt: (v) => set({ screenSelectedSt: v }),
  setIsConnectedToInternetSt: (v) => set({ isConnectedToInternetSt: v }),
  setWifiNameSt: (v) => set({ wifiNameSt: v }),
  setNetworkTypeSt: (v) => set({ networkTypeSt: v }),
  supabaseSetTimeoutSt: (v) => set({ supabaseTimeoutSt: v }),
  setRokuSearchModeSt: (v) => set({ rokuSearchModeSt: v }),
  setScreensSt: (v) => set({ screensSt: v }),
  setCableChannelsSt: (v) => set({ cableChannelsSt: v }),
  setYoutubeSearchVideosSt: (v) => set({ youtubeSearchVideosSt: v }),
  setYoutubeChannelsLizSt: (v) => set({ youtubeChannelsLizSt: v }),
  setYoutubeVideosLizSt: (v) => set({ youtubeVideosLizSt: v }),
  setRokuAppsSt: (v) => set({ rokuAppsSt: v }),
  setHdmiSalaSt: (v) => set({ hdmiSalaSt: v }),
  setDevicesSt: (v) => set({ devicesSt: v }),
  setRokuPlayStatePositionSt: (v) => set({ rokuPlayStatePositionSt: v }),
  setIsPcSt: (v) => set({ isPcSt: v }),
  setIsAppSt: (v) => set({ isAppSt: v }),
  setViewSt: (v) => set({ viewSt: v }),
  updateTablesSt: (tableName, newItem) => set((state) => ({ [tableName]: state[tableName].map((item) => item.id === newItem.id ? newItem : item) })),
  setTableSt: (tableName, newTable) => set({ [tableName]: newTable }),
  setPeersSt: (v) => set({ peersSt: v }),
  setLeaderSt: (v) => set({ leaderSt: v })
}));