export const devicesOriginal = {
    lamparaComedor: {
        state: 'off',
        label: 'Lampara Comedor',
        id: 'lamparaComedor',
        img: '/imgs/devices/lamparacomedor.png',
    },
    lamparaSala: {
        state: 'off',
        label: 'Lampara Sala',
        id: 'lamparaSala',
        img: '/imgs/devices/lamparasala.png',
    },
    lamparaTurca: {
        state: 'off',
        label: 'Lampara Turca',
        id: 'lamparaTurca',
        img: '/imgs/devices/lamparaturca.png',
    },
    lamparaLava: {
        state: 'off',
        label: 'Lampara Lava',
        id: 'lamparaLava',
        img: '/imgs/devices/lamparalava.png',
    },
    lamparaRotatoria: {
        state: 'off',
        label: 'Lampara Rotatoria',
        id: 'lamparaRotatoria',
        img: '/imgs/devices/lampararotatoria.png',
    },
    luzCuarto: {
        state: 'off',
        label: 'Luz Cuarto',
        id: 'luzCuarto',
        color: '',
        level: '',
        img: '/imgs/devices/luzcuarto.png',
    },
    luzEscalera: {
        state: 'off',
        label: 'Luz Escalera',
        id: 'luzEscalera',
        img: '/imgs/devices/luzescalera.png',
    },
    chimeneaSala: {
        state: 'off',
        label: 'Chimenea Sala',
        id: 'chimeneaSala',
        img: '/imgs/devices/chimeneasala.png',
    },
    ventiladorSala: {
        state: 'off',
        label: 'Ventilador Sala',
        id: 'ventiladorSala',
        img: '/imgs/devices/ventiladorsala.png',
    },
    lamparasAbajo: {
        state: 'off',
        label: 'Lamparas Abajo',
        id: 'lamparasAbajo',
        img: '/imgs/devices/lamparasabajo.png',
    },
    parlantesSala: {
        state: 'off',
        label: 'Parlantes Sala',
        id: 'parlantesSala',
        img: '/imgs/devices/parlantessala.png',
    },
    calentadorNegro: {
        state: 'off',
        label: 'Calentador Lizzie',
        id: 'calentadorNegro',
        img: '/imgs/devices/calentadornegro.png',
    },
    calentadorBlanco: {
        state: 'off',
        label: 'Calentador Amy',
        id: 'calentadorBlanco',
        img: '/imgs/devices/calentadorblanco.png',
    },
    hdmiSala: {
        state: 'roku',
        label: {
            roku: 'Roku',
            cable: 'Cable'
        },
        id: 'hdmiSala'
    },
    teleCuarto: {
        state: 'off',
        label: 'TV Cuarto',
        id: 'teleCuarto',
        mute: 'off',
        volume: '0',
        channelSelected: 'siete',
        input: {
            state: 'hdmi1',
            label: {
                hdmi1: 'Modo Normal',
                hdmi2: 'Modo Chromecast'
            }
        }
    },
    teleCocina: {
        state: 'off',
        label: 'TV Cocina',
        id: 'teleCocina',
        mute: 'off',
        volume: '0',
        channelSelected: 'siete',
        input: {
            state: 'hdmi1',
            label: {
                hdmi1: 'Modo Normal',
                hdmi2: 'Modo Chromecast'
            }
        }
    },
    teleSala: {
        state: 'off',
        label: 'TV Sala',
        id: 'teleSala',
        mute: 'off',
        volume: '0',
        channelSelected: 'siete',
        input: {
            state: 'hdmi1', 
            label: {
                hdmi1: 'Modo Normal',
                hdmi2: 'Modo Firestick'
            }
        }
    },
    proyectorSala: {
        state: 'off',
        label: 'Proyector',
        id: 'proyectorSala',
        mute: 'off',
        volume: '0',
        input: {
            state: 'hdmi1',
            label: {
                hdmi1: 'Modo Normal',
                hdmi2: 'Modo Playstation'
            }
        }
    },
    proyectorSwitchSala: {
        state: 'off',
        label: 'Proyector Switch Sala',
        id: 'proyectorSwitchSala'
    },
    rokuSala: {
        state: 'play',
        label: '',
        id: 'rokuSala',
        app: 'home',
        video: '',
        apps: {
            home: {
                label: 'Home',
                id: 'home',
                img: '/imgs/apps/netflix.png',
                rokuId: '562859',
            },
            netflix: {
                label: 'Netflix',
                id: 'netflix',
                img: '/imgs/apps/netflix.png',
                rokuId: '12',
            },
            disney: {
                label: 'Disney',
                id: 'disney',
                img: '/imgs/apps/disney.png',
                rokuId: '291097',
            },
            youtube: {
                label: 'Youtube',
                id: 'youtube',
                img: '/imgs/apps/youtube.png',
                rokuId: '837',
                videos: {
                    liz: [
                        {
                            label: 'Caillou goes camping',
                            description: 'Caillou goes camping',
                            id: '5tVd50YAJP0',
                            img: 'https://img.youtube.com/vi/5tVd50YAJP0/sddefault.jpg',
                            state: '',
                            channel: 'caillow',
                            date: '',
                            order: 0,
                        },
                        {
                            label: 'Caillou gets sick',
                            description: 'Caillou gets sick',
                            id: 'Z6dsdl76WGQ',
                            img: 'https://img.youtube.com/vi/Z6dsdl76WGQ/sddefault.jpg',
                            state: '',
                            channel: 'caillow',
                            date: '',
                            order: 0,
                        },
                    ],
                },
            },
            max: {
                label: 'Max',
                id: 'max',
                img: '/imgs/apps/max.png',
                rokuId: '61322',
            },
            amazon: {
                label: 'Amazon',
                id: 'amazon',
                img: '/imgs/apps/amazon.png',
                rokuId: '13',
            },
            pluto: {
                label: 'Pluto',
                id: 'pluto',
                img: '/imgs/apps/pluto.png',
                rokuId: '562859',
            }
        }
    },
    channelsSala: {
        selected: 'seis',
        channels: {
            tve: {
                order: 1,
                number: '03',
                ifttt: '1',
                label: 'Tve',
                id: 'tve',
                info: '',
                img: '/imgs/channels/tve.png',
                category: 'general',
            },
            cuatro: {
                order: 2,
                number: '04',
                ifttt: '1',
                label: 'Cuatro',
                id: 'cuatro',
                info: '',
                img: '/imgs/channels/cuatro.png',
                category: 'national',
            },
            seis: {
                order: 3,
                number: '06',
                ifttt: '1',
                label: 'Seis',
                id: 'seis',
                info: '',
                img: '/imgs/channels/seis.png',
                category: 'national',
            },
            siete: {
                order: 4,
                number: '07',
                ifttt: '1',
                label: 'Siete',
                id: 'siete',
                info: '',
                img: '/imgs/channels/siete.png',
                category: 'national',
            },
            multimedios: {
                order: 5,
                number: '08',
                ifttt: '1',
                label: 'Multimedios',
                id: 'multimedios',
                info: '',
                img: '/imgs/channels/multimedios.png',
                category: 'national',
            },
            nueve: {
                order: 6,
                number: '09',
                ifttt: '1',
                label: 'Nueve',
                id: 'nueve',
                info: '',
                img: '/imgs/channels/nueve.png',
                category: 'national',
            },
            estrellas: {
                order: 7,
                number: '10',
                ifttt: '1',
                label: 'Estrellas',
                id: 'estrellas',
                info: '',
                img: '/imgs/channels/estrellas.png',
                category: 'general',
            },
            once: {
                order: 8,
                number: '11',
                ifttt: '1',
                label: 'Once',
                id: 'once',
                info: '',
                img: '/imgs/channels/once.png',
                category: 'national',
            },
            sinart: {
                order: 9,
                number: '13',
                ifttt: '1',
                label: 'Sinart',
                id: 'sinart',
                info: '',
                img: '/imgs/channels/sinart.png',
                category: 'national',
            },
            xpertv: {
                order: 10,
                number: '14',
                ifttt: '1',
                label: 'Xpertv',
                id: 'xpertv',
                info: '',
                img: '/imgs/channels/xpertv.png',
                category: 'national',
            },
            ucr: {
                order: 11,
                number: '15',
                ifttt: '1',
                label: 'Ucr',
                id: 'ucr',
                info: '',
                img: '/imgs/channels/ucr.png',
                category: 'national',
            },
            tvchile: {
                order: 12,
                number: '16',
                ifttt: '1',
                label: 'Tv Chile',
                id: 'tvchile',
                info: '',
                img: '/imgs/channels/tvchile.png',
                category: 'general',
            },
            caracol: {
                order: 13,
                number: '17',
                ifttt: '1',
                label: 'Caracol',
                id: 'caracol',
                info: '',
                img: '/imgs/channels/caracol.png',
                category: 'general',
            },
            uno: {
                order: 14,
                number: '31',
                ifttt: '1',
                label: 'Canal 1',
                id: 'uno',
                info: '',
                img: '/imgs/channels/uno.png',
                category: 'national',
            },
            tvn: {
                order: 15,
                number: '32',
                ifttt: '1',
                label: 'Tvn 14',
                id: 'tvn',
                info: '',
                img: '/imgs/channels/tvn.png',
                category: 'national',
            },
            tvsur: {
                order: 16,
                number: '33',
                ifttt: '1',
                label: 'Tv Sur',
                id: 'tvsur',
                info: '',
                img: '/imgs/channels/tvsur.png',
                category: 'national',
            },
            trivision: {
                order: 17,
                number: '36',
                ifttt: '1',
                label: 'Trivision',
                id: 'trivision',
                info: '',
                img: '/imgs/channels/trivision.png',
                category: 'national',
            },
            telemundo: {
                order: 18,
                number: '100',
                ifttt: '1',
                label: 'Telemundo',
                id: 'telemundo',
                info: '',
                img: '/imgs/channels/telemundo.png',
                category: 'general',
            },
            azcorazon: {
                order: 19,
                number: '101',
                ifttt: '1',
                label: 'Az Corazon',
                id: 'azcorazon',
                info: '',
                img: '/imgs/channels/azcorazon.png',
                category: 'soapopera',
            },
            gourmet: {
                order: 20,
                number: '105',
                ifttt: '1',
                label: 'Gourmet',
                id: 'gourmet',
                info: '',
                img: '/imgs/channels/gourmet.png',
                category: 'food',
            },
            homeandhealth: {
                order: 21,
                number: '106',
                ifttt: '2',
                label: 'Home And Health',
                id: 'homeandhealth',
                info: '',
                img: '/imgs/channels/homeandhealth.png',
                category: 'lifestyle',
            },
            maschic: {
                order: 22,
                number: '107',
                ifttt: '2',
                label: 'Mas Chic',
                id: 'maschic',
                info: '',
                img: '/imgs/channels/maschic.png',
                category: 'lifestyle',
            },
            telexitos: {
                order: 23,
                number: '109',
                ifttt: '2',
                label: 'Telexitos',
                id: 'telexitos',
                info: '',
                img: '/imgs/channels/telexitos.png',
                category: 'series',
            },
            hogartv: {
                order: 24,
                number: '110',
                ifttt: '2',
                label: 'Hogar tv',
                id: 'hogartv',
                info: '',
                img: '/imgs/channels/hogartv.png',
                category: 'lifestyle',
            },
            lifetime: {
                order: 25,
                number: '111',
                ifttt: '2',
                label: 'Lifetime',
                id: 'lifetime',
                info: '',
                img: '/imgs/channels/lifetime.png',
                category: 'movies',
            },
            holatv: {
                order: 26,
                number: '112',
                ifttt: '2',
                label: 'Hola tv',
                id: 'holatv',
                info: '',
                img: '/imgs/channels/holatv.png',
                category: 'lifestyle',
            },
            univision: {
                order: 27,
                number: '113',
                ifttt: '2',
                label: 'Univision',
                id: 'univision',
                info: '',
                img: '/imgs/channels/univision.png',
                category: 'lifestyle',
            },
            filmandarts: {
                order: 28,
                number: '115',
                ifttt: '2',
                label: 'Film and Arts',
                id: 'filmandarts',
                info: '',
                img: '/imgs/channels/filmandarts.png',
                category: 'movies',
            },
            foodnetworkes: {
                order: 29,
                number: '116',
                ifttt: '2',
                label: 'Food Network Es',
                id: 'foodnetworkes',
                info: '',
                img: '/imgs/channels/foodnetworkes.png',
                category: 'food',
            },
            foodnetworkus: {
                order: 30,
                number: '117',
                ifttt: '2',
                label: 'Food Network Us',
                id: 'foodnetworkus',
                info: '',
                img: '/imgs/channels/foodnetworkus.png',
                category: 'food',
            },
            hgtv: {
                order: 31,
                number: '118',
                ifttt: '2',
                label: 'Hgtv',
                id: 'hgtv',
                info: '',
                img: '/imgs/channels/hgtv.png',
                category: 'lifestyle',
            },
            cartoon: {
                order: 32,
                number: '125',
                ifttt: '2',
                label: 'Cartoon',
                id: 'cartoon',
                info: '',
                img: '/imgs/channels/cartoon.png',
                category: 'children',
            },
            nick: {
                order: 33,
                number: '127',
                ifttt: '2',
                label: 'Nick',
                id: 'nick',
                info: '',
                img: '/imgs/channels/nick.png',
                category: 'children',
            },
            cartoonito: {
                order: 34,
                number: '128',
                ifttt: '2',
                label: 'Cartoonito',
                id: 'cartoonito',
                info: '',
                img: '/imgs/channels/cartoonito.png',
                category: 'children',
            },
            nickjr: {
                order: 35,
                number: '129',
                ifttt: '2',
                label: 'Nick jr',
                id: 'nickjr',
                info: '',
                img: '/imgs/channels/nickjr.png',
                category: 'children',
            },
            disney: {
                order: 36,
                number: '130',
                ifttt: '2',
                label: 'Disney',
                id: 'disney',
                info: '',
                img: '/imgs/channels/disney.png',
                category: 'children',
            },
            discoverykids: {
                order: 37,
                number: '131',
                ifttt: '2',
                label: 'Discovery Kids',
                id: 'discoverykids',
                info: '',
                img: '/imgs/channels/discoverykids.png',
                category: 'children',
            },
            disneyjr: {
                order: 38,
                number: '132',
                ifttt: '2',
                label: 'Disney Jr',
                id: 'disneyjr',
                info: '',
                img: '/imgs/channels/disneyjr.png',
                category: 'children',
            },
            tooncast: {
                order: 39,
                number: '133',
                ifttt: '2',
                label: 'Tooncast',
                id: 'tooncast',
                info: '',
                img: '/imgs/channels/tooncast.png',
                category: 'children',
            },
            nickmusic: {
                order: 40,
                number: '134',
                ifttt: '2',
                label: 'Nick Music',
                id: 'nickmusic',
                info: '',
                img: '/imgs/channels/nickmusic.png',
                category: 'children',
            },
            clan: {
                order: 41,
                number: '135',
                ifttt: '3',
                label: 'Clan',
                id: 'clan',
                info: '',
                img: '/imgs/channels/clan.png',
                category: 'children',
            },
            history2: {
                order: 42,
                number: '174',
                ifttt: '3',
                label: 'History 2',
                id: 'history2',
                info: '',
                img: '/imgs/channels/history2.png',
                category: 'science',
            },
            natgeo: {
                order: 43,
                number: '176',
                ifttt: '3',
                label: 'Nat Geo',
                id: 'natgeo',
                info: '',
                img: '/imgs/channels/natgeo.png',
                category: 'science',
            },
            discovery: {
                order: 44,
                number: '177',
                ifttt: '3',
                label: 'Discovery',
                id: 'discovery',
                info: '',
                img: '/imgs/channels/discovery.png',
                category: 'science',
            },
            animalplanet: {
                order: 45,
                number: '178',
                ifttt: '3',
                label: 'Animal Planet',
                id: 'animalplanet',
                info: '',
                img: '/imgs/channels/animalplanet.png',
                category: 'science',
            },
            history: {
                order: 46,
                number: '179',
                ifttt: '3',
                label: 'History',
                id: 'history',
                info: '',
                img: '/imgs/channels/history.png',
                category: 'science',
            },
            tlc: {
                order: 47,
                number: '180',
                ifttt: '3',
                label: 'TLC',
                id: 'tlc',
                info: '',
                img: '/imgs/channels/tlc.png',
                category: 'science',
            },
            curiosity: {
                order: 48,
                number: '181',
                ifttt: '3',
                label: 'Curiosity',
                id: 'curiosity',
                info: '',
                img: '/imgs/channels/curiosity.png',
                category: 'science',
            },
            cnnesp: {
                order: 49,
                number: '202',
                ifttt: '3',
                label: 'CNN Español',
                id: 'cnnesp',
                info: '',
                img: '/imgs/channels/cnnesp.png',
                category: 'news',
            },
            cnnint: {
                order: 50,
                number: '203',
                ifttt: '3',
                label: 'CNN International',
                id: 'cnnint',
                info: '',
                img: '/imgs/channels/cnnint.png',
                category: 'news',
            },
            cnbc: {
                order: 51,
                number: '205',
                ifttt: '3',
                label: 'CNBC',
                id: 'cnbc',
                info: '',
                img: '/imgs/channels/cnbc.png',
                category: 'news',
            },
            bbc: {
                order: 52,
                number: '206',
                ifttt: '3',
                label: 'BBC',
                id: 'bbc',
                info: '',
                img: '/imgs/channels/bbc.png',
                category: 'news',
            },
            foxnews: {
                order: 53,
                number: '207',
                ifttt: '3',
                label: 'Fox News',
                id: 'foxnews',
                info: '',
                img: '/imgs/channels/foxnews.png',
                category: 'news',
            },
            cnnusa: {
                order: 54,
                number: '208',
                ifttt: '3',
                label: 'CNN USA',
                id: 'cnnusa',
                info: '',
                img: '/imgs/channels/cnnusa.png',
                category: 'news',
            },
            bloomberg: {
                order: 55,
                number: '209',
                ifttt: '3',
                label: 'Bloomberg',
                id: 'bloomberg',
                info: '',
                img: '/imgs/channels/bloomberg.png',
                category: 'news',
            },
            rt: {
                order: 56,
                number: '210',
                ifttt: '3',
                label: 'RT Español',
                id: 'rt',
                info: '',
                img: '/imgs/channels/rt.png',
                category: 'news',
            },
            headlinenews: {
                order: 57,
                number: '211',
                ifttt: '3',
                label: 'Headline News',
                id: 'headlinenews',
                info: '',
                img: '/imgs/channels/headlinenews.png',
                category: 'news',
            },
            calaweather: {
                order: 58,
                number: '212',
                ifttt: '3',
                label: 'Cala Weather',
                id: 'calaweather',
                info: '',
                img: '/imgs/channels/calaweather.png',
                category: 'news',
            },
            ticavision: {
                order: 59,
                number: '213',
                ifttt: '3',
                label: 'Tica Vision',
                id: 'ticavision',
                info: '',
                img: '/imgs/channels/ticavision.png',
                category: 'news',
            },
            horas24: {
                order: 60,
                number: '214',
                ifttt: '3',
                label: '24 Horas',
                id: 'horas24',
                info: '',
                img: '/imgs/channels/horas24.png',
                category: 'news',
            },
            tdmas: {
                order: 61,
                number: '221',
                ifttt: '4',
                label: 'TD Mas',
                id: 'tdmas',
                info: '',
                img: '/imgs/channels/tdmas.png',
                category: 'sports',
            },
            tdmas2: {
                order: 62,
                number: '222',
                ifttt: '4',
                label: 'TD Mas 2',
                id: 'tdmas2',
                info: '',
                img: '/imgs/channels/tdmas2.png',
                category: 'sports',
            },
            tigosports: {
                order: 63,
                number: '223',
                ifttt: '4',
                label: 'Tigo Sports',
                id: 'tigosports',
                info: '',
                img: '/imgs/channels/tigosports.png',
                category: 'sports',
            },
            futv: {
                order: 64,
                number: '224',
                ifttt: '4',
                label: 'FUTV',
                id: 'futv',
                info: '',
                img: '/imgs/channels/futv.png',
                category: 'sports',
            },
            espn5: {
                order: 65,
                number: '225',
                ifttt: '4',
                label: 'ESPN 5',
                id: 'espn5',
                info: '',
                img: '/imgs/channels/espn5.png',
                category: 'sports',
            },
            espn: {
                order: 66,
                number: '226',
                ifttt: '4',
                label: 'ESPN',
                id: 'espn',
                info: '',
                img: '/imgs/channels/espn.png',
                category: 'sports',
            },
            espn4: {
                order: 67,
                number: '227',
                ifttt: '4',
                label: 'ESPN 4',
                id: 'espn4',
                info: '',
                img: '/imgs/channels/espn4.png',
                category: 'sports',
            },
            espn2: {
                order: 68,
                number: '228',
                ifttt: '4',
                label: 'ESPN 2',
                id: 'espn2',
                info: '',
                img: '/imgs/channels/espn2.png',
                category: 'sports',
            },
            tycsports: {
                order: 69,
                number: '229',
                ifttt: '4',
                label: 'Tyc Sports',
                id: 'tycsports',
                info: '',
                img: '/imgs/channels/tycsports.png',
                category: 'sports',
            },
            goltv: {
                order: 70,
                number: '230',
                ifttt: '4',
                label: 'Gol Tv',
                id: 'goltv',
                info: '',
                img: '/imgs/channels/goltv.png',
                category: 'sports',
            },
            tudn: {
                order: 71,
                number: '231',
                ifttt: '4',
                label: 'TUDN',
                id: 'tudn',
                info: '',
                img: '/imgs/channels/tudn.png',
                category: 'sports',
            },
            espn6: {
                order: 72,
                number: '232',
                ifttt: '4',
                label: 'ESPN 6',
                id: 'espn6',
                info: '',
                img: '/imgs/channels/espn6.png',
                category: 'sports',
            },
            espn3: {
                order: 73,
                number: '234',
                ifttt: '4',
                label: 'ESPN 3',
                id: 'espn3',
                info: '',
                img: '/imgs/channels/espn3.png',
                category: 'sports',
            },
            dreamworks: {
                order: 74,
                number: '272',
                ifttt: '4',
                label: 'Dreamworks',
                id: 'dreamworks',
                info: '',
                img: '/imgs/channels/dreamworks.png',
                category: 'movies',
            },
            sonymovies: {
                order: 75,
                number: '273',
                ifttt: '4',
                label: 'Sony Movies',
                id: 'sonymovies',
                info: '',
                img: '/imgs/channels/sonymovies.png',
                category: 'movies',
            },
            hbo: {
                order: 76,
                number: '274',
                ifttt: '4',
                label: 'Hbo',
                id: 'hbo',
                info: '',
                img: '/imgs/channels/hbo.png',
                category: 'movies',
            },
            universal: {
                order: 77,
                number: '275',
                ifttt: '4',
                label: 'Universal',
                id: 'universal',
                info: '',
                img: '/imgs/channels/universal.png',
                category: 'movies',
            },
            golden: {
                order: 78,
                number: '276',
                ifttt: '4',
                label: 'Golden',
                id: 'golden',
                info: '',
                img: '/imgs/channels/golden.png',
                category: 'movies',
            },
            cinelatino: {
                order: 79,
                number: '277',
                ifttt: '4',
                label: 'Cine Latino',
                id: 'cinelatino',
                info: '',
                img: '/imgs/channels/cinelatino.png',
                category: 'movies',
            },
            space: {
                order: 80,
                number: '278',
                ifttt: '4',
                label: 'Space',
                id: 'space',
                info: '',
                img: '/imgs/channels/space.png',
                category: 'movies',
            },
            cinecanal: {
                order: 81,
                number: '280',
                ifttt: '5',
                label: 'Cinecanal',
                id: 'cinecanal',
                info: '',
                img: '/imgs/channels/cinecanal.png',
                category: 'movies',
            },
            cinemax: {
                order: 82,
                number: '281',
                ifttt: '5',
                label: 'cinemax',
                id: 'cinemax',
                info: '',
                img: '/imgs/channels/cinemax.png',
                category: 'movies',
            },
            tnt: {
                order: 83,
                number: '282',
                ifttt: '5',
                label: 'tnt',
                id: 'tnt',
                info: '',
                img: '/imgs/channels/tnt.png',
                category: 'movies',
            },
        }
    }
};

