export const createAppSlice = (set) => ({
    // --- Global states ---
    sendEnabledSt: true,
    simulatePlayStateSt: false,
    isLoadingSt: false,
    isLoadInitializedSt: false,
    themeSt: 'dark',
    isInForegroundSt: true,
    isConnectedToInternetSt: true,
    wifiNameSt: '',
    networkTypeSt: '',
    isConnectedToNokySt: false,
    isPcSt: false,
    isAppSt: false,
    lizEnabledSt: false,
    viewSt: { selected: '', cable: { channels: { category: [] } }, roku: { apps: { selected: '', youtube: { mode: '', channel: '' } } }, devices: { device: '' } },

    // --- Actions ---
    setSendEnabledSt: (v) => set({ sendEnabledSt: v }),
    setSimulatePlayStateSt: (v) => set({ simulatePlayStateSt: v }),
    setIsLoadingSt: (v) => set({ isLoadingSt: v }),
    setThemeSt: (v) => set({ themeSt: v }),
    setIsInForegroundSt: (v) => set({ isInForegroundSt: v }),
    setIsConnectedToInternetSt: (v) => set({ isConnectedToInternetSt: v }),
    setWifiNameSt: (v) => set({ wifiNameSt: v }),
    setNetworkTypeSt: (v) => set({ networkTypeSt: v }),
    setIsPcSt: (v) => set({ isPcSt: v }),
    setIsAppSt: (v) => set({ isAppSt: v }),
    setViewSt: (v) => set({ viewSt: v }),
    setLizEnabledSt: (v) => set({ lizEnabledSt: v }),
    setIsConnectedToNokySt: (v) => set({ isConnectedToNokySt: v }),
    setIsLoadInitializedSt: (v) => set({ isLoadInitializedSt: v }),
});
